# Generated by Django 5.2.10 on 2026-03-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_agentprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='phone',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
